name: Compile and upload ZIP files

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  create-linux-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          FILES="
          app.py
          learn.py
          filepicker.py
          vocab_io.py
          edit_vocab_file.py
          about.py
          VocabularyPlus.tcss
          icons/
          installation/
          LICENSE
          README.md
          "

          zip -r "VocabularyPlus.zip" $FILES

      - name: Upload assets to existing release
        uses: softprops/action-gh-release@v2
        with:
          files: VocabularyPlus.zip
          tag_name: ${{ github.event.release.tag_name }}
          append_body: false